---
- name: install postgresql94 repo
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-2.noarch.rpm state=present
  tags: postgresql
- name: install postgresql94
  yum: name=postgresql94-server state=present
  tags: postgresql
- name: check /var/lib/pgsql/9.4/data/postgresql.conf exists
  stat: path=/var/lib/pgsql/9.4/data/postgresql.conf
  register: f
  tags: postgresql
- name: initdb -E UTF8 --no-locale
  command: bash -lc "/usr/pgsql-9.4/bin/initdb -E UTF8 --no-locale"
  sudo_user: postgres
  when: not f.stat.exists
  tags: postgresql
- name: start postgresql
  service: name=postgresql-9.4 state=started enabled=yes
  when: not f.stat.exists
  tags: postgresql
